site:
  name: "The Jalapeno"
  base: "/"

metadata:
  title: 
    default: "Jalapeno Blog Site"
    template: "%s | Jalapeno"
  description: "Personal blog site"

i18n:
  languages:
    - code: "en"
      label: "English"
 
#https://github.com/berts/astro_astrowind
apps:
  blog:
    isEnable: true
    postsPerPage: 5